name: Run Python Tests
on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Install Python 3
              uses: actions/setup-python@v2
              with:
                  python-version: 3.9.11
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install --editable .[test]
            - name: Run tests with pytest
              run: python -m pytest ./Test --emoji
